.\"
.\" Copyright (c) 2023 James Addison <jay@jp-hosting.net>
.\"
.\" This file was written for inclusion in the 'quadrilateralcowboy' package
.\" for Debian.
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <https://www.gnu.org/licenses/>.
.TH "QC" 6 "2023-02-08" "QC"
.SH NAME
qc - Quadrilateral Cowboy: a first-person cyberpunk adventure game
.SH INTRODUCTION
The engine noise from your jetbike rises to a loud purr and then gradually
subsides after you press your foot down on the pedal, adding a small burst of
acceleration to navigate the final segment of the near-pitch-black railway
tunnel.

Your adrenaline levels are rising, the way that they always do at the start of
a new job.  Almost ritually, you relax momentarily on the bike, don your
headphones, and reach for your pocket vinylman.

You press 'play', and there's a satisfying 'ch-click' sound as the blocky
plastic button locks into place.

You and your team emerge from the tunnel into the cool evening air, swinging
your bikes into position alongside the tracks.  The train gradually overtakes,
and, over the gentle tones of Debussy's 'Clair de Lune', you hear the doppler-\
shifting sound of a bell as it swings from side-to-side on one of the
carriages.

It's time to get to work...
.SH AUTHORS
.B qc
was written and developed by Blendo Games <http://www.blendogames.com>.
.P
This manual page was written by James Addison <jay@jp-hosting.net>.
